### ISSUE TITLE
How to use for Apollo Client 2.0

### ISSUE THREAD

**Issue by leojh** [af/apollo-local-query#12]
The `ApolloClient` object in the new 2.0 version requires that both `link` and `cache` be passed in. How is this library supposed to be used in 2.0?

**Comment by nick** [comment]
Please see https://github.com/apollographql/apollo-link/issues/158

**Comment by af** [comment]
Thanks @nick! I haven't kicked the tires on Apollo Client 2.0 but my understanding was that this package would basically be obsolete– seems the networking side of things is completely different in 2.0. I'll add a note about this in the readme for future visitors

**Comment by af** [comment]
Actually @nick on second thought, are you planning on publishing ApolloLinkLocal as a separate package? Maybe we could join forces and distribute it as v2 of `apollo-local-query` here instead?

**Comment by nick** [comment]
@seeden wrote the code I ended up using and mentioned he was planning to release it as a module - perhaps he can take you up on the offer as I wouldn't want to take credit for his work 😄

**Comment by af** [comment]
Oh thanks! I had scrolled down and missed that your code was derived from his. I'll follow that thread and see where it goes, I agree with you that any functionality that's necessary for SSR would ideally be included in Apollo Client anyways.

**Comment by vladshcherbin** [comment]
@af maybe you can take this code if the author doesn't mind and release it as a new version of this package?

v1 - for apollo v1
v2 - for apollo v2

This will be super useful.

**Comment by vladshcherbin** [comment]
I've been using this package with apollo v1 and would be happy to update and use it with v2.

**Comment by af** [comment]
Thanks @VladShcherbin, I considered repurposing the code, but it looked like @seeden was intending to publish it himself. I'm definitely on board for having the v2 code live here if Apollo doesn't include it.

**Comment by leojh** [comment]
Thank you. It looks like I actually do not need a local Apollo client as I now realize that I can query directly as follows: `graphql(schema, query).then((result) => console.log('Got result', result))`

**Comment by nick** [comment]
It looks like this is now in core: https://www.apollographql.com/docs/link/links/schema.html

**Comment by af** [comment]
Yes, I added a note about that to the readme this morning. Let me know if it can be worded more clearly. 

We had a good run, `apollo-local-query`
