### ISSUE TITLE
Using this results in my server-side rendering locking up

### ISSUE THREAD

**Issue by curio77** [af/apollo-local-query#3]
I'm trying to use this in the context of [react-starter-kit](https://github.com/kriasoft/react-starter-kit). After integrating [apollo-client](https://github.com/apollostack/apollo-client) according to its docs I proceeded to incorporate this similarly straightforwardly. However, for me this causes server-side rendering to lock up (browser times out) without throwing any errors, so I'm somewhat clueless as to the cause (and how to go about debugging it). Any ideas?

**Comment by af** [comment]
Hi,
Thanks for the report. Can you try running your app with debug output enabled (ie `DEBUG=apollo-local npm start`) and see if anything from this module gets logged? You could also add another `debug()` call before the try/catch in `query()` to make sure it's getting called.

**Comment by curio77** [comment]
Sorry about the trouble: it turns out I was simply using the wrong `import` syntax instead of the `require` given in the docs. Things now work as expected, thanks! :-)
