### ISSUE TITLE
How about dataIdFromObject?

### ISSUE THREAD

**Issue by petergarnaes** [af/apollo-local-query#4]
Great library! However, an apollo client has the option of giving an [`dataIdFromObject` option](http://dev.apollodata.com/react/cache-updates.html#dataIdFromObject) which is for caching in the browser. But this library has no such option, so when rehydrating the store everything gets the wrong ID's in the store. Is there a simple fix I am overlooking?

**Comment by af** [comment]
@petergarnaes what was the workaround for the issue? I haven't used `dataIdFromObject` myself, but I haven't run into any issues with caching yet either

**Comment by petergarnaes** [comment]
@af It is just me being an idiot, they are indeed unrelated. `dataIdFromObject` is an option given to the apollo client, it has nothing to do with the network interface...

**Comment by af** [comment]
Ah ok no problem, thanks for the update!
