### ISSUE TITLE
Error: only absolute urls are supported

### ISSUE THREAD

**Issue by ravikiran438** [af/apollo-local-query#8]
I am getting the following error, am I missing something?

Error: only absolute urls are supported
       at /app_root/node_modules/node-fetch/index.js:54:10

**Comment by af** [comment]
@ravikiran438 I'm not sure, but this module doesn't depend on fetch directly (Apollo does, though). Can you share some of your code?

**Comment by af** [comment]
Closing, unless there's more context showing this is actually a problem with this module
